### ISSUE TITLE
Error: Recipes not found!! null 

### ISSUE THREAD

**Issue by shipsywor** [animsh/Appita#1]
The app shows the error message "Recipes not found!! null" on launch.

I added proper API_KEY in Constants. I checked the API_KEY works in postman.

What is the fix?

**Comment by animsh** [comment]
If you are running the code, then first go into the recipeviewmodel and in applyquery function remove all the queries except api key and recipe number and run the code, it will work fine then add that removed queries again and run the code. It's api issue it returns null on first call with lots of queries in app
For now this is only fix, I will try to fix it asap
